services:
  - type: web
    name: loan-management-system
    runtime: docker # This tells Render to use your Dockerfile
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:file:./data/loandb