services:
  - type: web
    name: loan-management-system
    runtime: image
    image:
      url: render/java:17 # Or 21 if you are using Java 21
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/loan-management-system-0.0.1-SNAPSHOT.jar
    disk:
      name: loandb-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1